# Generated by Django 2.2 on 2020-05-19 23:01

from django.db import migrations, models
import tube.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tube.models.get_file_path)),
            ],
        ),
    ]
