# Generated by Django 2.2 on 2020-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Default title', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
